// Writes the plugdash parts of the real EmDash site:
// - astro.config.mjs registering every package that exports a descriptor
// - companion components on the blog post page, each inside a #pd-* element
// - src/pages/s/[code].astro while shortlink still ships RedirectPage.astro
// Usage: node write-site.mjs <repoRoot> <siteDir>
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [root, site] = process.argv.slice(2);

const pkgs = readdirSync(join(root, "packages"))
	.map((dir) => JSON.parse(readFileSync(join(root, "packages", dir, "package.json"), "utf8")))
	.filter((p) => !p.private);

// Every package with a main entry gets registered with no options, the way
// the READMEs tell users to start. The factory is the export named <name>Plugin
// (createPlugin is the native runtime entry, not a descriptor).
const withEntry = pkgs.filter((p) => p.exports?.["."]);
const imports = withEntry.map((p, i) => `import * as p${i} from "${p.name}";`).join("\n");
const plugins = withEntry.map((_, i) => `descriptor(p${i})`).join(", ");

writeFileSync(
	join(site, "astro.config.mjs"),
	`// Generated by plugdash scripts/real-emdash/write-site.mjs - do not edit.
import node from "@astrojs/node";
import react from "@astrojs/react";
import { defineConfig, fontProviders } from "astro/config";
import emdash, { local } from "emdash/astro";
import { sqlite } from "emdash/db";
${imports}

function descriptor(mod) {
	const factory = Object.entries(mod).find(
		([name, value]) =>
			name.endsWith("Plugin") && name !== "createPlugin" && typeof value === "function",
	);
	if (!factory) throw new Error("no *Plugin export in " + Object.keys(mod).join(", "));
	return factory[1]();
}

export default defineConfig({
	output: "server",
	adapter: node({ mode: "standalone" }),
	image: { layout: "constrained", responsiveStyles: true },
	integrations: [
		react(),
		emdash({
			database: sqlite({ url: "file:./data.db" }),
			storage: local({ directory: "./uploads", baseUrl: "/_emdash/api/media/file" }),
			plugins: [${plugins}],
		}),
	],
	fonts: [
		{
			provider: fontProviders.google(),
			name: "Inter",
			cssVariable: "--font-body",
			weights: [400, 500, 600, 700],
			fallbacks: ["sans-serif"],
		},
		{
			provider: fontProviders.google(),
			name: "JetBrains Mono",
			cssVariable: "--font-mono",
			weights: [400, 500],
			fallbacks: ["monospace"],
		},
	],
	devToolbar: { enabled: false },
});
`,
);

// Companion components. Skipped when a package no longer exports the file.
const components = [
	["pd-readtime", "@plugdash/readtime", "ReadingTime"],
	["pd-toc", "@plugdash/tocgen", "TableOfContents"],
	["pd-share", "@plugdash/sharepost", "ShareButtons"],
	["pd-heart", "@plugdash/heartpost", "HeartButton"],
	["pd-copy", "@plugdash/shortlink", "CopyLink"],
	["pd-engage", "@plugdash/engage", "EngagementBar"],
].filter(([, name, comp]) => pkgs.find((p) => p.name === name)?.exports?.[`./${comp}.astro`]);

const postPage = join(site, "src/pages/posts/[slug].astro");
const original = join(site, "src/pages/posts/[slug].astro.orig");
if (!existsSync(original)) writeFileSync(original, readFileSync(postPage));
let page = readFileSync(original, "utf8");

const componentImports = components
	.map(([, name, comp]) => `import ${comp} from "${name}/${comp}.astro";`)
	.join("\n");
const markup = components
	.map(([id, , comp]) => `\t\t\t\t<div id="${id}"><${comp} post={post} /></div>`)
	.join("\n");

page = page.replace("---\n", `---\n${componentImports}\n`);
const anchor = '\t\t\t\t<div class="article-comments">';
if (!page.includes(anchor)) throw new Error("post page anchor not found, template changed?");
page = page.replace(anchor, `<!-- plugdash -->\n${markup}\n\n${anchor}`);
writeFileSync(postPage, page);

// Shortlink redirect page, until shortlink moves to native redirects (card #10)
const shortlink = pkgs.find((p) => p.name === "@plugdash/shortlink");
if (shortlink?.exports?.["./RedirectPage.astro"]) {
	mkdirSync(join(site, "src/pages/s"), { recursive: true });
	writeFileSync(
		join(site, "src/pages/s/[code].astro"),
		'---\nimport RedirectPage from "@plugdash/shortlink/RedirectPage.astro";\n---\n<RedirectPage />\n',
	);
} else {
	rmSync(join(site, "src/pages/s"), { recursive: true, force: true });
}

console.log(
	`real-emdash: registered ${withEntry.map((p) => p.name).join(", ")}; components: ${components.map((c) => c[0]).join(", ")}`,
);
